Update first.yml

diff --git a/.github/workflows/first.yml b/.github/workflows/first.yml
--- a/.github/workflows/first.yml
+++ b/.github/workflows/first.yml
@@ -92,9 +92,9 @@ jobs:
           echo "Host=[$SSH_HOST]"
           echo "User=[$SSH_USER]"
           echo "Key length=$(echo "$SSH_PRIVATE_KEY" | wc -c)"
-          [ -z "$SSH_HOST" ] && echo "❌ Missing SSH_HOST" && exit 1
-          [ -z "$SSH_USER" ] && echo "❌ Missing SSH_USER" && exit 1
-          [ -z "$SSH_PRIVATE_KEY" ] && echo "❌ Missing SSH_PRIVATE_KEY" && exit 1
+          [ -z $SSH_HOST ] && echo "❌ Missing SSH_HOST" && exit 1
+          [ -z $SSH_USER ] && echo "❌ Missing SSH_USER" && exit 1
+          [ -z $SSH_PRIVATE_KEY ] && echo "❌ Missing SSH_PRIVATE_KEY" && exit 1
 
       
       - name: Deploy over SSH
