Enhance script with error handling and exports
Added error handling and environment variable exports to the script.

diff --git a/.github/workflows/first.yml b/.github/workflows/first.yml
--- a/.github/workflows/first.yml
+++ b/.github/workflows/first.yml
@@ -97,6 +97,9 @@ jobs:
           envs: GITHUB_SHA,GITHUB_REPOSITORY
           script_stop: true
           script: |
+            set -Eeuo pipefail
+            trap 'echo "[ERROR] $BASH_COMMAND (line $LINENO)
+             실패" >&2' ERR
             set -e
             export IMAGE_SHA="${GITHUB_SHA}"
             export GH_OWNER="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
